name: Refresh caches

on:
  workflow_dispatch:
# push:
#   branches: [ "main" ]

env:
  BUILD_TYPE: Release
  
jobs:
  linux-cache-update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache/restore@v3
      id: restore
      with:
        path: ${{github.workspace}}/build
        key: linux-placeholder
        restore-keys: linux-
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCB_BUILD_DOCS=OFF -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - uses: actions/cache/save@v3
      id: save
      with:
        key: linux-${{ github.sha }}
  windows-cache-update:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache/restore@v3
      id: restore
      with:
        path: ${{github.workspace}}/build
        key: windows-placeholder
        restore-keys: windows-
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCB_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - uses: actions/cache/save@v3
      id: save
      with:
        key: windows-${{ github.sha }}
      
        
      
